### ISSUE TITLE
Issues with all three Tunisian Channels 

### ISSUE THREAD

**Issue by ltai0001** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1068]
### Describe the bug
For both Watania TV channels I am getting list index out of range error line 37 in get_live_url. 
Upon further investigation it appears the live streams are m3u8 type by looking at the html source of the websites

Both streams were successfully tested with VLC Media/open network stream menu

For Watania 1 Channel: http://live.watania1.tn:1935/live/watanya1.stream/playlist.m3u8
For Watania 2 Channel: http://live.watania2.tn:1935/live/watanya2.stream/playlist.m3u8

### To Reproduce
Steps to reproduce the behaviour:
1. launch Watania 1 or Watania 2 live stream from the addon menu
2.
3.
4.

### Expected behaviour
should see the live streams play without an erro as they are not geolocked 

### Actual behaviour
get a list index out of range line 37 in watania.py

### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [X] Raspberry-Pi
 - [X] Windows
 - [ ] Other

 - Operating system version/name:
 - Kodi version: 19
 - Catch-up TV & More version: 0.2.38+matrix.1
 - Installation method:

### Additional context
Add any other context about the problem here:

### Debug log
https://paste.kodi.tv/lohogigoje.kodi

**Comment by joaopa00** [comment]
Should be fixed in git.

**Comment by ltai0001** [comment]
this is still an issue - running 0.2.39~beta18 on windows getting errors still
[](https://paste.kodi.tv/ulusexobay)

**Comment by joaopa00** [comment]
Did you have tested the latest beta (19) or GIT?
The fix is not in the beta 18, so why did you test it?
