### ISSUE TITLE
Cnews H.S. a nouveau...

### ISSUE THREAD

**Issue by gilles0606** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1445]
Bonsoir,

Voilà les trace, avec la version d'il y a deux jours.
(elle fonctionnais le jour de la sortie, samedi)

Merci 

2024-12-16 19:16:30.550 T:1267    error <general>: [Catch-up-TV-&-More.support] 403 Client Error: Forbidden for url: https://www.cnews.fr/les-replays
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 306, in run_callback
                                                       redirect = parent_ins(route, arg_params, self.callback_params)
                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/script.module.codequick/lib/codequick/route.py", line 196, in __call__
                                                       session_data = self._process_results(results)
                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/script.module.codequick/lib/codequick/route.py", line 210, in _process_results
                                                       listitems = validate_listitems(results)
                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/script.module.codequick/lib/codequick/route.py", line 39, in validate_listitems
                                                       raw_listitems = list(raw_listitems)
                                                                       ^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/fr/cnews.py", line 85, in list_emissions
                                                       resp = urlquick.get(URL_REPLAY_CNEWS, headers=GENERIC_HEADERS, max_age=-1)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/script.module.codequick/lib/urlquick.py", line 492, in get
                                                       return request('get', url, params=params, **kwargs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/script.module.codequick/lib/urlquick.py", line 486, in request
                                                       return s.request(method=method, url=url, **kwargs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/script.module.codequick/lib/urlquick.py", line 441, in request
                                                       self._raise_for_status(response, raise_for_status)
                                                     File "/storage/.kodi/addons/script.module.codequick/lib/urlquick.py", line 414, in _raise_for_status
                                                       response.raise_for_status()
                                                     File "/storage/.kodi/addons/script.module.requests/lib/requests/models.py", line 1021, in raise_for_status
                                                       raise HTTPError(http_error_msg, response=self)
                                                   requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://www.cnews.fr/les-replays
2024-12-16 19:16:30.552 T:1267    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'HTTPError' object has no attribute 'code'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.catchuptvandmore/addon.py", line 23, in <module>
                                                       main()
                                                     File "/storage/.kodi/addons/plugin.video.catchuptvandmore/addon.py", line 19, in main
                                                       main.error_handler(exception)
                                                     File "/storage/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/main.py", line 297, in error_handler
                                                       code = exception.code
                                                              ^^^^^^^^^^^^^^
                                                   AttributeError: 'HTTPError' object has no attribute 'code'
                                                   -->End of Python script error report<--
                                                   
2024-12-16 19:16:30.639 T:1266    error <general>: GetDirectory - Error getting plugin://plugin.video.catchuptvandmore/resources/lib/channels/fr/cnews/list_emissions/?_pickle_=80049598000000000000007d94288c075f7469746c655f948c0e4e6f7320c3a96d697373696f6e73948c076974656d5f6964948c05636e657773948c0c63617465676f72795f75726c948c4968747470733a2f2f7777772e636e6577732e66722f736572766963652f646d5f6c6f61646d6f72652f646d5f656d697373696f6e5f696e6465785f656d697373696f6e732f25732f30948c0470616765948c013094752e
2024-12-16 19:16:30.644 T:1003    error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.catchuptvandmore/resources/lib/channels/fr/cnews/list_emissions/?_pickle_=80049598000000000000007d94288c075f7469746c655f948c0e4e6f7320c3a96d697373696f6e73948c076974656d5f6964948c05636e657773948c0c63617465676f72795f75726c948c4968747470733a2f2f7777772e636e6577732e66722f736572766963652f646d5f6c6f61646d6f72652f646d5f656d697373696f6e5f696e6465785f656d697373696f6e732f25732f30948c0470616765948c013094752e) failed

**Comment by Wind06** [comment]
Même soucis pour moi

**Comment by joaopa00** [comment]
Should be fixed in git. Thanks for Jeff200 to have had a look at this.

**Comment by Wind06** [comment]
Apparently still not or king for me, on a Sony TV

Httperror
403 client error: forbiden for url:https://www.cnews.fr/le-direct

thanks.

**Comment by jeff2900** [comment]
Fixed in PR #1447 but not yet commit.
You can donwloand and install manually https://www.mediafire.com/file/w7jpmdtqhjva8xx/plugin.video.catchuptvandmore-0.2.40%257Ebeta18-fix-cnews.zip/file

**Comment by joaopa00** [comment]
Il y a un patch dejà dan la beta18 qui devrait etre équivalent à celui de JEFF2900. Il serait bon de savoir quelle version utilise WIND06.

**Comment by Wind06** [comment]
Merci pour la réponse, j’utilise la version 0.2.40-beta18 avec cette version ça ne fonctionnait pas.
Je viens d’installer 

https://www.mediafire.com/file/w7jpmdtqhjva8xx/plugin.video.catchuptvandmore-0.2.40%257Ebeta18-fix-cnews.zip/file

sur la 0.2.40-beta18, et maintenant ça fonctionne.

au Top merci à tous 😊
