### ISSUE TITLE
Large amount of Japanese TV Channels do not play shows (404 client error)

### ISSUE THREAD

**Issue by KylanHaffie** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1481]
### Describe the bug
Many Japanese TV shows on various channels now do not play, giving a 404 client error not found when attempting to be played. 

Few channels still work (such as TV Tokyo)

### To Reproduce
Steps to reproduce the behaviour:
1. Catch-up TV < Japan < TVER: ABC
2. Select any program
3. Select any episode 
404 client error occurs 

### Expected behaviour
The episode should play 

### Actual behaviour
The episode does not play and a 404 client error occurs 

I've tested this on two different devices in android environments.

**Comment by kalun85** [comment]
Got the same issue on windows devices.  Initially I thought it was VPN being the issue, but tried without VPN, still the same issue.

Looking at the Kodi.log, here is a sample stack trace:

2025-03-22 10:53:00.819 T:6776    error <general>: [Catch-up-TV-&-More.support] 404 Client Error: Not Found for url: https://edge.api.brightcove.com/playback/v1/accounts/6191645753001/videos/ref:Ft6iro6di_3qk
                                                   Traceback (most recent call last):
                                                     File "C:\Users\Media Center\AppData\Roaming\Kodi\addons\script.module.codequick\lib\codequick\support.py", line 306, in run_callback
                                                       redirect = parent_ins(route, arg_params, self.callback_params)
                                                     File "C:\Users\Media Center\AppData\Roaming\Kodi\addons\script.module.codequick\lib\codequick\resolver.py", line 67, in __call__
                                                       results = super(Resolver, self).__call__(route, args, kwargs)
                                                     File "C:\Users\Media Center\AppData\Roaming\Kodi\addons\script.module.codequick\lib\codequick\script.py", line 169, in __call__
                                                       return route.function(self, *args, **kwargs)
                                                     File "C:\Users\Media Center\AppData\Roaming\Kodi\addons\plugin.video.catchuptvandmore\resources\lib\channels\jp\tver.py", line 120, in get_video_url
                                                       return resolver_proxy.get_brightcove_video_json(plugin, data_account, data_player, data_video_id, None, download_mode)
                                                     File "C:\Users\Media Center\AppData\Roaming\Kodi\addons\plugin.video.catchuptvandmore\resources\lib\resolver_proxy.py", line 410, in get_brightcove_video_json
                                                       resp = urlquick.get(URL_BRIGHTCOVE_VIDEO_JSON % (data_account, data_video_id), headers=headers)
                                                     File "C:\Users\Media Center\AppData\Roaming\Kodi\addons\script.module.codequick\lib\urlquick.py", line 492, in get
                                                       return request('get', url, params=params, **kwargs)
                                                     File "C:\Users\Media Center\AppData\Roaming\Kodi\addons\script.module.codequick\lib\urlquick.py", line 486, in request
                                                       return s.request(method=method, url=url, **kwargs)
                                                     File "C:\Users\Media Center\AppData\Roaming\Kodi\addons\script.module.codequick\lib\urlquick.py", line 441, in request
                                                       self._raise_for_status(response, raise_for_status)
                                                     File "C:\Users\Media Center\AppData\Roaming\Kodi\addons\script.module.codequick\lib\urlquick.py", line 414, in _raise_for_status
                                                       response.raise_for_status()
                                                     File "C:\Users\Media Center\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\models.py", line 1021, in raise_for_status
                                                       raise HTTPError(http_error_msg, response=self)
                                                   requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://edge.api.brightcove.com/playback/v1/accounts/6191645753001/videos/ref:Ft6iro6di_3qk

**Comment by joaopa00** [comment]
Looks like TVER changed its api. It  is not Brightvoce anymore

**Comment by joaopa00** [comment]
Fixed in beta. Unfortunately, TVER is geoblocked now.

**Comment by kalun85** [comment]
Thanks, tested new tver.py with VPN to Japan, seems to be working.

**Comment by Ahsune** [comment]
On our Nvidia Shield TV using Kodi, shows before the error still play, but shows uploaded after the error are still producing the 404 error for Brightcove. We even uninstalled and reinstalled the beta version and no luck. Can anyone help?

**Comment by kalun85** [comment]
@Ahsune just replace the tver.py with the updated one here: https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/blob/dev/resources/lib/channels/jp/tver.py

**Comment by joaopa00** [comment]
Fixed in beta.

**Comment by Ahsune** [comment]
Awesome! It worked. Thank you 🙂
