### ISSUE TITLE
Fresh install on Kodi 19 : codequick session request fail - 6Play and RTLPlay (live TV and Replay KO)

### ISSUE THREAD

**Issue by enigma131** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#447]
### Describe the bug
After a fresh install of the plug-in over Kodi 19, i got error message for some channels

### To Reproduce
1. install the plugin by normal way ,  choosing  beta
2. get a 6 play account , and fill the plugin section
3. accept install widewine
4. chose m6 or w9 as channel as for kodi 18.9

### Expected behavior
Can watch the channel

### Actual behavior
Got error message

### Your environment
 - Operating system version/name: Linux Mint 20.1
 - Kodi version: 19.0 final
 - Catch-up TV & More version: beta 2.32.1
 - Installation method: normal way  https://catch-up-tv-and-more.github.io/installation/#ii-add-the-official-catch-up-tv--more-repository

### Additional context
Add any other context about the problem here:

### Debug log
partial log: 
2021-02-27 11:32:02.408 T:4142    ERROR <general>: [Catch-up-TV-&-More.support] sequence item 1: expected a bytes-like object, str found
                                                   Traceback (most recent call last):
                                                     File "/home/toto/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 306, in run_callback
                                                       redirect = parent_ins(route, arg_params, self.callback_params)
                                                     File "/home/toto/.kodi/addons/script.module.codequick/lib/codequick/resolver.py", line 67, in __call__
                                                       results = super(Resolver, self).__call__(route, args, kwargs)
                                                     File "/home/toto/.kodi/addons/script.module.codequick/lib/codequick/script.py", line 169, in __call__
                                                       return route.function(self, *args, **kwargs)
                                                     File "/home/toto/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/fr/6play.py", line 550, in get_live_url
                                                       resp2 = urlquick.post(
                                                     File "/home/toto/.kodi/addons/script.module.codequick/lib/urlquick.py", line 505, in post
                                                       return request('post', url, data=data, json=json, **kwargs)
                                                     File "/home/toto/.kodi/addons/script.module.codequick/lib/urlquick.py", line 482, in request
                                                       return s.request(method=method, url=url, **kwargs)
                                                     File "/home/toto/.kodi/addons/script.module.codequick/lib/urlquick.py", line 436, in request
                                                       response = super(Session, self).request(*args, **kwargs)
                                                     File "/home/toto/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 533, in request
                                                       resp = self.send(prep, **send_kwargs)
                                                     File "/home/toto/.kodi/addons/script.module.codequick/lib/urlquick.py", line 445, in send
                                                       return super(Session, self).send(request, **kwargs)
                                                     File "/home/toto/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 646, in send
                                                       r = adapter.send(request, **kwargs)
                                                     File "/home/toto/.kodi/addons/script.module.codequick/lib/urlquick.py", line 349, in send
                                                       urlhash = hash_url(request)
                                                     File "/home/toto/.kodi/addons/script.module.codequick/lib/urlquick.py", line 203, in hash_url
                                                       return hashlib.sha1(b''.join((data, req.body or b''))).hexdigest()
                                                   TypeError: sequence item 1: expected a bytes-like object, str found

**Comment by wwark** [comment]
Thank you @enigma131 
Ticket to follow the issue : https://github.com/willforde/urlquick/issues/13

**Comment by enigma131** [comment]
Thanks, he have fixed, fine
I've had look onto Fedora 33 that is working, the codequick is version "0.9.14" and Ubuntu / LM 20 fresh install have "1.0.1+matrix.1" . Not same youtube.dl + htmlement involved!

**Comment by wwark** [comment]
Yes Kodi 18 used python 2 and have version dedicated for it on the officiel repo of Kodi same as Kodi 19 with python3.
We proposed two version of CUTV&More one for Kodi 17/18 and one for Kodi 19.

**Comment by enigma131** [comment]
No no Fedora 33 have Kodi 19 final too. Codequick is not same version and Fedora 33 haven't the bug. If it can help...

**Comment by wwark** [comment]
Weird .. is Fedora proposed his own plugin for Kodi ?

**Comment by enigma131** [comment]
Some of them yes. Example all PVRs are compiled by RPMfusion

**Comment by wwark** [comment]
PVR it is normal because it is binary addon (compiled for the OS).
But if it is the case for CodeQuick, it means it can work like you described but normally it will not the case regarding the issue ...
It means the support depends of Fedora ... because they don't use the one officially proposed by Kodi ...

If I take an example CUTV&More used a function available on codequick version 1.0.1 it means Kodi for Fedora with our plugin will failed ...
I don't think it is a good way and the only response we can propose to you in this case will be to upgrade codequick ...

**Comment by enigma131** [comment]
Yes when all is fixed, in I will reinstall CUTV&More on Fedora 33 by normal way, I had no choice at Fedora 33 starting :+1:

**Comment by enigma131** [comment]
I have replaced urlquick.py on LM 20.1 distribution by the one from willforde repo and all is working now. Waiting official version for testing Fedora 33, Windows and Android.

**Comment by jiemeb** [comment]
I have same issue for 6 play group on kodi 19 on ubuntu 20.04
  [Catch-up-TV-&-More.support] sequence item 1: expected a bytes-like object, str found

**Comment by kaioh31** [comment]
Hello,
I have exactly the same issue here, with Kodi 19 install on Nvidia Shield or Windows 10
`[Catch-up-TV-&-More.support] sequence item 1: expected a bytes-like object, str found`
Regards.

**Comment by kaioh31** [comment]
Here is my full log file if needed : https://paste.kodi.tv/dabadixuwe.kodi

Regards.

**Comment by wwark** [comment]
CodeQuick 1.0.2 has been added on the repo Kodi 19 (Matrix)
https://github.com/xbmc/repo-scripts/pull/1902

The version for Kodi 18 Leia is still reviewed but will be avaialble soon.

**Comment by enigma131** [comment]
Yep, but still not loaded on Linux distros:
![Codequick_Matrix](https://user-images.githubusercontent.com/31815445/110104357-59879400-7da7-11eb-8ec8-02fb39d894ab.png)
I reboot on LM 20.1 so see

**Comment by kaioh31** [comment]
> CodeQuick 1.0.2 has been added on the repo Kodi 19 (Matrix)
> [xbmc/repo-scripts#1902](https://github.com/xbmc/repo-scripts/pull/1902)
> 
> The version for Kodi 18 Leia is still reviewed but will be avaialble soon.

Hello Wwark,
Is it available on stable or beta repo for Kodi 19 (or both) ?
Regards.

**Comment by enigma131** [comment]
@ kaioh31 : I'm on beta

**Comment by wwark** [comment]
The notion of beta and stable are for our own repo.
Maybe it takes time to synch official repo of Kodi 19 where CodeQuick is publish.

Thanks.

**Comment by wwark** [comment]
Normally codequick can be updated to 1.0.2 on Kodi 19.
Is this issue is fixed on your side ?

Thanks,

**Comment by kaioh31** [comment]
Hi guys,
Issue fixed on my side on both Windows and Nvidia Shield.
Just had to update Codequick and it worked.
But I have the feeling that it takes more time to launch a M6 replay (40sec). Once it is launched, no problem to navigate, so I have excluded bandwidth issue.
Thank you for your reactivity, you're awesome ! :)
Regards !

**Comment by enigma131** [comment]
Got codequick 1.0.2 on Fedora 33 with Kodi 19. Now all is working on all my linux,  France TV, M6 group and programm info

**Comment by jiemeb** [comment]
with codequick 1.0.2 replay et live 6play is OK
Thank's

**Comment by wwark** [comment]
Thanks for your returns.
We will close this ticket in the begining of the next week to be sure everyone gets the new version of codequick 1.0.2

**Comment by enigma131** [comment]
This issue is fixed everywhere for me now, all linux, windows 10 and android 10, could be closed for me yes . Thanks

**Comment by Gaet81** [comment]
Hello,

Did you update manually?
I still don't have the codequick 1.0.2 when I check the version in Matrix...

Regards,

Gaëtan

**Comment by chocky95** [comment]
same as kaioh, working with code quick 1.0'2 on android 9 (xiaomi mi box s)
but th elaunch of m6 or w9 channel is very long  (several minutes). for other channels, it is one second. do you have an idea ?
Code quick 1.0.2
inputstream 0.5.2
youtube dl 21.302
iptv manager 0.2.3
htmlelement 1.0.0
thanks

**Comment by wwark** [comment]
We will open a new ticket issue for the case for several minutes to launch the video in 6Play on Kodi 19 with an android device.
I see some persons not have codequik 1.0.2 so we will let this ticket opened.
Thanks.

**Comment by kaioh31** [comment]
Hello Wwark,
I have the same behavior on Kodi installed on Windows 10.
Regards,
K.

**Comment by wwark** [comment]
The new ticket for the long time to load content in 6PLay (and RTLPlay)
https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/463
This topic will be follow in this ticket.

**Comment by wwark** [comment]
New version fixed those issues available.
