### ISSUE TITLE
Live TV Arte (FR) and Arte (DE) failed to load with HTTP Error 404

### ISSUE THREAD

**Issue by SimonClavier** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#546]
### Describe the bug
Live International Arte (FR) and Arte (DE) failed to load.
Popup Error
"**HTTP Error**
404 Client Error: Not Found for url: https://static-cdn.arte.tv/guide/manifest.js"

### To Reproduce
1. KODI
2. TV
3. Channels
4. Arte (FR)

### Expected behavior
View the channel live

### Actuel behavior
Error Message pop up 
"**HTTP Error**
404 Client Error: Not Found for url: https://static-cdn.arte.tv/guide/manifest.js"

### Screenshots
_If applicable, add screenshots to help explain your problem:_
useless

### Your environment
 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Other

 - Operating system version/name: Ubuntu 20.04.2 LTS
 - Kodi version: Kodi (19.1 (19.1.0) Git:20210509-85e05228b4). Platform: Linux x86 64-bit
 - Catch-up TV & More version: 0.2.35+matrix 1
 - Installation method: cf. https://catch-up-tv-and-more.github.io/fr/installation/

### Additional context
_Add any other context about the problem here:_
Problem signaled also in #544 but incompletly

### Debug log
_If you can, please add your debug log information (Tutorial available here: https://kodi.wiki/view/Log_file/Easy):_
Here is an xtract of the kodi.log
```
Catch-up-TV-&-More.support] 404 Client Error: Not Found for url: https://static-cdn.arte.tv/guide/manifest.js
File "/home/xxxx/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/wo/arte.py", line 590, in get_live_url
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://static-cdn.arte.tv/guide/manifest.js
```

**Comment by ouinouin** [comment]
hi, same here with kodi in libreelec environment.

**Comment by staffly** [comment]
Hi, Same problem here on :
- OSMC v. 19.1.0 Git 20210803
- IPTV Simple v. 7.6.9
- Catchup-tv v. 0.2.36-beta08

**Comment by sy6sy2** [comment]
Hi all!
Thank you for this issue. Can you try version 0.2.36~beta09 on the beta repo please? It should fix this issue.

**Comment by Pollinopops** [comment]
Hi, just tried the 0.2.36~beta09 version. It doesn't fix the issue for me

**Comment by enigma131** [comment]
Beta 09 is working here. Host Linux with Kodi 19.1

**Comment by Pollinopops** [comment]
> @Pollinopops thank you for the test. Do you have the issue for Arte live FR or Arte live DE?
> 
> Concerning Arte replay (#543), I am working on it.

Oh sorry, it's Arte replay that still isn't working. Thank you for your amazing work on this plugin !!

**Comment by staffly** [comment]
Hey all,
It's working now (Catchup-tv v. 0.2.36-beta12) but the video quality seems to be stuck at 320x180. I have no problem with other channels, and default quality is set to BEST in the plugin settings. Any idea?

**Comment by SimonClavier** [comment]
Hello !
1/ Thanks for the update ! 0.2.3-beta12 fixed indeed the problem ! Sorry fo my late answer ...
2/ I experience exactlly the same problem as @staffly, I'm stuck in poor quality 320x180
