### ISSUE TITLE
Catch-Up Tv Japan

### ISSUE THREAD

**Issue by kalun85** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#752]
### Describe the bug
Tver.jp updated their site April 1, 2022.  As a result, Japan Content from Catch-Up TV is broken.

### To Reproduce
Steps to reproduce the behaviour:
1. Open Catch-Up TV all
2. Go to Catchup content
3. Select Japan > any station > all content

### Expected behaviour
A list of content being displayed

### Actual behaviour
The page keeps loading, with Attribute Error. 

### Your environment
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ X] OSX
 - [X ] Raspberry-Pi
 - [ ] Windows
 - [ ] Other

**Comment by joaopa00** [comment]
In a browser, I do not manage to watch any video. I tried firefox (I receive an error and google chrome: I received <<watch with the appli>>) How do you do to watch video in a browser?

**Comment by kalun85** [comment]
@joaopa00 VPN to Japan.  In the code, I think it works because it uses brightcove to replay.

**Comment by joaopa00** [comment]
Even with a vpn, I can not watch any video.

**Comment by kalun85** [comment]
chrome and firefox all worked for me.  

If you see this error message: "広告をブロックするプラグインが有効になっている場合、無効にしてから再度お試しください。" it's due to adblocker.

**Comment by joaopa00** [comment]
![With google chrome](https://user-images.githubusercontent.com/13057733/161331839-6b58ba6b-67a7-4510-9910-291b59a90770.png)

**Comment by kalun85** [comment]
@joaopa00 Here is what I see and the firefox version I am using.
![tver1](https://user-images.githubusercontent.com/684251/161338094-1b8651ad-2dc5-450f-9182-f0fb1776895c.png)
![tver2](https://user-images.githubusercontent.com/684251/161338105-f8023695-5d07-43d6-87b8-e7257615eb87.png)

If you go to the console in web developer, what do you see? (3 strip on upper right hand corner > More Tools > Web Developer Tool > Console)

![tver3](https://user-images.githubusercontent.com/684251/161338379-19db32d3-1bd0-433e-8aeb-fa1a19091426.png)

**Comment by joaopa00** [comment]
![Capture d’écran_2022-04-01_11-46-34](https://user-images.githubusercontent.com/13057733/161345674-03da46ba-1196-448b-9072-4234c16c71e1.png)

**Comment by kalun85** [comment]
um...this is clearly a nextjs error. 

You are getting the same screen as:
https://nextjs.org/docs/messages/client-side-exception/occurred

If you really want to drill down to it, probably need to use the debugger:
https://nextjs.org/docs/advanced-features/debugging#client-side-code

**Comment by joaopa00** [comment]
OK. I fixed the firefox problem by removing the cache folder.

**Comment by joaopa00** [comment]
Does anyone konw how to fetch all the videos? On the new site, I see only 300 videos.
On the old site [old site](https://webcache.googleusercontent.com/search?q=cache:soUbnIvg--8J:https://tver.jp/cx+&cd=2&hl=fr&ct=clnk&gl=fr)
only for fujitv it seems there are much more videos.

**Comment by kalorg** [comment]
[kodi_log.log](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/8520807/kodi_log.log)

Japan Content from Catch-Up TV is broken
Error : [Catch-up-TV-&-More.support] 'NoneType' object has no attribute 'findall'

It's my kodi or problem with tver ?

No problem with french content.

Thanks

**Comment by joaopa00** [comment]
Tver changed its api. So Catchuptvandmore is broken with Tver. Unfortunately, Tver"s api is  very difficult to understand. It will take a moment to implement it in catchuptvandmore. Sorry.

**Comment by kalun85** [comment]
@joaopa00 did a bit of digging, I think here is probably a good way to get the info:

1. Create User

Use the following:

https://platform-api.tver.jp/v2/api/platform_users/browser/create

With x-www-form-urlencoded payload as device_type = pc

Here is the sample payload response:

{
    "api_version": "v2",
    "code": 0,
    "message": "",
    "type": "hash",
    "result": {
        "platform_uid": "9670a8040a8f4d5b854645ec124963405ac5",
        "platform_ad_uuid": "6d7c02d2-ff9b-44b6-9d63-b66d99a4dbae",
        "platform_token": "fwgatznapas6esh9cbyt9f4e8nbtl9dv9ktbmp8d",
        "browser_id": "pootii6qedsn8vhxrze71ecch4ntpvradnly",
        "device_type": "pc",
        "agreement_version": ""
    }
}

2. use platform_uid and platform_token to call HTTP Get.  Here is a sample URL:

https://platform-api.tver.jp/service/api/v1/callSearch?platform_uid=9670a8040a8f4d5b854645ec124963405ac5&platform_token=fwgatznapas6esh9cbyt9f4e8nbtl9dv9ktbmp8d&required_data=later

Payload is a bit long, it gets the most recent 1000 videos.  Here is one of they episode in the list:

 {
                "type": "episode",
                "content": {
                    "id": "epa5584pxq",
                    "version": 2,
                    "title": "第3話",
                    "isNHKContent": false,
                    "seriesTitle": "中国ドラマ☆ トキメキ雲上学堂スキャンダル～漂亮書生～",
                    "isAvailable": true,
                    "broadcasterName": "テレビ東京",
                    "productionProviderName": "ＢＳテレ東",
                    "broadcastDateLabel": "4月8日(金)放送分"
                },
                "isLater": false,
                "favoriteCount": 3113,
                "tags": [
                    {
                        "id": "comedy",
                        "name": "コメディ"
                    },
                    {
                        "id": "drama",
                        "name": "ドラマ"
                    },
                    {
                        "id": "romance",
                        "name": "恋愛"
                    },
                    {
                        "id": "teen",
                        "name": "青春"
                    },
                    {
                        "id": "txn",
                        "name": "テレビ東京系"
                    }
                ]
            },

3. Using information above, call GET https://statics.tver.jp/content/[type]/[id].json?v=v2.0.0

Example Request:
https://statics.tver.jp/content/episode/epzu55siqh.json?v=v2.0.0

Example Result:

{
    "id": "epzu55siqh",
    "version": 4,
    "video": {
        "videoID": "6304479332001",
        "accountID": "3971130137001",
        "playerID": "Eyc2R2Jow",
        "channelID": "tx"
    },
    "title": " ",
    "seriesID": "srv8vo5zlb",
    "seasonID": "ssaeihcxnu",
    "description": "男たちの身勝手な欲望により、身も心も傷つけられた2人の女性が男たちへ立ち向かう、衝撃のクライムラブサスペンス！　「寂しい丘で狩りをする」をご紹介!!　テレビ東京にて、月曜 深夜2時35分・火曜 深夜3時5分・水曜 深夜3時5分・木曜 深夜3時35分・金曜 午前10時48分・金曜 深夜3時より放送中！",
    "no": 7,
    "broadcastProviderLabel": "テレビ東京",
    "productionProviderLabel": "テレビ東京",
    "broadcastDateLabel": "4月20日(水)放送分",
    "broadcastProviderID": "tx",
    "isSubtitle": false,
    "copyright": "（C）TV TOKYO",
    "viewStatus": {
        "startAt": 1650510003,
        "endAt": 1651114799
    },
    "isAllowCast": true,
    "share": {
        "text": "今から行きたい至極グルメ ほほおちゴハン！\n#TVer",
        "url": "https://tver.jp/lp/episodes/epzu55siqh"
    },
    "tags": {},
    "isNHKContent": false,
    "svod": []
}

The url is the link to each of the episodes.

Hope it helps :)

**Comment by joaopa00** [comment]
Thank you for your help. But I am stuck at stage 2:
`import requests

resp = requests.post("https://platform-api.tver.jp/v2/api/platform_users/browser/create", data={'device_type': 'pc'})
data = resp.json()

uid = data['result']['platform_uid']
token = data['result']['platform_token']
print('token = {}'.format(token))
print('uid = {}'.format(uid))
url = 'https://platform-api.tver.jp/service/api/v1/callSearch?platform_uid={}&platform_token={}&required_data=later'.format(uid, token)
print('url = %s' %url)
resp2 = requests.get(url, data={'device_type': 'pc'})
print(resp2)
`

How did you manage to have the stage 2 working?

Thanks in advance.

**Comment by kalun85** [comment]
oh, don't mentioned it

For stage 2, don't need payload, but need a header field:

'x-tver-platform-type':'web'

Not really good at python, but this worked for me:
=======================
import requests

platform_uid = 'a6a9da4d6a844baa8ccbbbbb02d7d46bcd09'
platform_token = '6m9k2mnk4xhnuj5xzsimmq6wu4ub58eqxdej86p5'

required_data = 'later'
tver_url = 'https://platform-api.tver.jp/service/api/v1/callSearch'

tver_header = {'x-tver-platform-type':'web'}
tver_params = {'platform_uid': platform_uid, 'platform_token': platform_token}

response = requests.get(tver_url, params=tver_params, headers=tver_header)

print(response.json())
===================

**Comment by joaopa00** [comment]
Thanks, that works. Header was missing. With header, it is OK.

**Comment by joaopa00** [comment]
Do you know a way to fetch the name of the program?
For instance, for this program, I do not know its name
https://statics.tver.jp/content/episode/epzu55siqh.json?v=v2.0.0

**Comment by kalorg** [comment]
it's on json with request https://platform-api.tver.jp/service/api/v1/callSearch

you have id (epzu55siqh), name of serie, and title. 

If you need to know the name with just id is :
https://service-api.tver.jp/api/v1/callEpisode/epzu55siqh

**Comment by kalun85** [comment]
There are 2 ways I know, 

1. First is from stage 2, there is a seriesTitle in content:

{
                "type": "episode",
                "content": {
                    "id": "epg876h8w8",
                    "version": 6,
                    "title": "ゴリけん、パラシュート部隊のドキュメンタリーバラエティ",
                    "isNHKContent": false,
                    _"**seriesTitle": "ゴリパラ見聞録",**_
                    "isAvailable": true,
                    "broadcasterName": "フジテレビ",
                    "productionProviderName": "テレビ西日本",
                    "broadcastDateLabel": "4月22日(金)放送分"
                },

2. Next is another lookup, using the seriesID.  So first lookup is stage 3 and grab the series ID:

https://statics.tver.jp/content/episode/epzu55siqh.json?v=v2.0.0

{
    "id": "epzu55siqh",
    "version": 4,
    "video": {
        "videoID": "6304479332001",
        "accountID": "3971130137001",
        "playerID": "Eyc2R2Jow",
        "channelID": "tx"
    },
    "title": " ",
    **_"seriesID": "srv8vo5zlb",_**
    "seasonID": "ssaeihcxnu",
    "description": "男たちの身勝手な欲望により、身も心も傷つけられた2人の女性が男たちへ立ち向かう、衝撃のクライムラブサスペンス！　「寂しい丘で狩りをする」をご紹介!!　テレビ東京にて、月曜 深夜2時35分・火曜 深夜3時5分・水曜 深夜3時5分・木曜 深夜3時35分・金曜 午前10時48分・金曜 深夜3時より放送中！",
    "no": 7,
    "broadcastProviderLabel": "テレビ東京",
    "productionProviderLabel": "テレビ東京",
    "broadcastDateLabel": "4月20日(水)放送分",
    "broadcastProviderID": "tx",
    "isSubtitle": false,
    "copyright": "（C）TV TOKYO",
    "viewStatus": {
        "startAt": 1650510003,
        "endAt": 1651114799
    },
    "isAllowCast": true,
    "share": {
        "text": "今から行きたい至極グルメ ほほおちゴハン！\n#TVer",
        "url": "https://tver.jp/lp/episodes/epzu55siqh"
    },
    "tags": {},
    "isNHKContent": false,
    "svod": []
}

Then another lookup to the series, and grab the title field:
https://statics.tver.jp/content/series/**[series ID]**.json?v=v2.0.0

Example:
https://statics.tver.jp/content/series/srv8vo5zlb.json?v=v2.0.0

{
    "id": "srv8vo5zlb",
    "version": 6,
    **_"title": "今から行きたい至極グルメ ほほおちゴハン！",_**
    "startDateLabel": "",
    "description": "≪ハマりびと≫の熱い沼トークと共に、ほほがおちる＝“ほほおち”するほどおいしい激うまグルメ情報を奥深くお届けします。",
    "broadcastProvider": {
        "name": "テレビ東京",
        "copyright": "（C）TV TOKYO"
    },
    "official": {
        "siteURL": "https://www.tv-tokyo.co.jp/hohoochigohan/",
        "twitterURL": ""
    },
    "share": {
        "text": "今から行きたい至極グルメ ほほおちゴハン！\n#TVer",
        "url": "https://tver.jp/lp/series/srv8vo5zlb"
    },
    "svod": [],
    "viewStartAt": 0,
    "isNHKContent": false
}

**Comment by joaopa00** [comment]
Can you give a try with this version of development?
https://github.com/joaopa00/plugin.video.catchuptvandmore/archive/refs/heads/dev.zip

If everything looks fine for you, il will push it in the repo.

**Comment by kalun85** [comment]
sure, will let you know in a few hours :)  thanks for updating the code.

**Comment by kalun85** [comment]
@joaopa00  tried, didn't work when select Japan on Catch-Up menu.  Here is the kodi log, looks like just a typo on formating JSON:

2022-04-23 16:35:03.449 T:27550    INFO <general>: initializing python engine.
2022-04-23 16:35:04.343 T:27550   ERROR <general>: [Catch-up-TV-&-More.support] invalid syntax (jp_replay.py, line 110)
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 306, in run_callback
                                                       redirect = parent_ins(route, arg_params, self.callback_params)
                                                     File "/storage/.kodi/addons/script.module.codequick/lib/codequick/route.py", line 196, in __call__
                                                       session_data = self._process_results(results)
                                                     File "/storage/.kodi/addons/script.module.codequick/lib/codequick/route.py", line 210, in _process_results
                                                       listitems = validate_listitems(results)
                                                     File "/storage/.kodi/addons/script.module.codequick/lib/codequick/route.py", line 39, in validate_listitems
                                                       raw_listitems = list(raw_listitems)
                                                     File "/storage/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/main.py", line 61, in generic_menu
                                                       menu = get_sorted_menu(plugin, menu_id)
                                                     File "/storage/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/menu_utils.py", line 129, in get_sorted_menu
                                                       current_menu = importlib.import_module('resources.lib.skeletons.' +
                                                     File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
                                                     File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
                                                     File "<frozen importlib._bootstrap>", line 991, in _find_and_load
                                                     File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
                                                     File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
                                                     File "<frozen importlib._bootstrap_external>", line 779, in exec_module
                                                     File "<frozen importlib._bootstrap_external>", line 916, in get_code
                                                     File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
                                                     File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
                                                     File "/storage/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/skeletons/jp_replay.py", line 110
                                                       'label': 'TVER: ','中京テレビ',
                                                                                ^
                                                   SyntaxError: invalid syntax

**Comment by joaopa00** [comment]
My bad. Sorry for the trouble. Should be fixed. Please test again
https://github.com/joaopa00/plugin.video.catchuptvandmore/archive/refs/heads/dev.zip

**Comment by kalun85** [comment]
@joaopa00 tried the new version, still having issue, this time, it got to TVER: [Channel] selection screen, when selecting TVER:  日テレ、got error:

2022-04-23 18:45:24.007 T:889     ERROR <general>: [Catch-up-TV-&-More.support] invalid syntax (tver.py, line 40)           
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 300, in run_callback
                                                       route = self.get_route(self.selector)                                                     
                                                     File "/storage/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 248, in get_route
                                                       importlib.import_module(module_path)
                                                     File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
                                                     File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
                                                     File "<frozen importlib._bootstrap>", line 991, in _find_and_load
                                                     File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
                                                     File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
                                                     File "<frozen importlib._bootstrap_external>", line 779, in exec_module
                                                     File "<frozen importlib._bootstrap_external>", line 916, in get_code
                                                     File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
                                                     File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
                                                     File "/storage/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/jp/tver.py", line 40
'tbs': {'TBS', 'TUYテレビユー山形', 'CBCテレビ', 'RKK熊本放送', 'HBC北海道放送', 'BS-TBS', 'MRO', 'RCCテレビ', 'BSN', 'TUFテレビユー福島', 'SBC信越放送'},
                                                            ^                                                   SyntaxError: invalid syntax

**Comment by joaopa00** [comment]
Sorry for the trouble. Can you give a new try? I hope everything is fine now.

**Comment by kalun85** [comment]
@joaopa00  sure, do you want to send me a new version?

**Comment by joaopa00** [comment]
Should not be matter. But anyway, I did the modification.
For me, I fall in unauthorized action...

**Comment by kalun85** [comment]
Downloaded the new version.  Syntax error did go away after modification.  Afterward, I was able to select the program and I got the same error as you:

2022-04-23 21:30:31.828 T:901     ERROR <general>: [Catch-up-TV-&-More.support] 401 Client Error: Unauthorized for url: https://edge.api.brightcove.com/playback/v1/accounts/4394098882001/videos/ref:ce6d3535-54b6-440e-85a3-5fb39e3e2e5c?User-Agent=Opera%2F9.80+%28X11%3B+Linux+i686%3B+Ubuntu%2F14.10%29+Presto%2F2.12.388+Version%2F12.16&Accept=application%2Fjson%3Bpk%3DBCpkADawqM1l5pA4XtMLusHj72LGzFewqKZzldpmNYTUQdoKnFL_GHhN3dg5FRnNQ5V7SOUKBl-tYFMt8CpSzuSzFAPhIHtVwmMz6F52VnMfu2UjDmeYfvvUqk0CWon46Yh-CZwIVp5vfXrZ&X-Forwarded-For=
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 306, in run_callback
                                                       redirect = parent_ins(route, arg_params, self.callback_params)
                                                     File "/storage/.kodi/addons/script.module.codequick/lib/codequick/resolver.py", line 67, in __call__
                                                       results = super(Resolver, self).__call__(route, args, kwargs)
                                                     File "/storage/.kodi/addons/script.module.codequick/lib/codequick/script.py", line 169, in __call__
                                                       return route.function(self, *args, **kwargs)
                                                     File "/storage/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/jp/tver.py", line 115, in get_video_url
                                                       resp = urlquick.get(URL_JSON_VIDEO, headers)
                                                     File "/storage/.kodi/addons/script.module.codequick/lib/urlquick.py", line 493, in get
                                                       return request('get', url, params=params, **kwargs)
                                                     File "/storage/.kodi/addons/script.module.codequick/lib/urlquick.py", line 487, in request
                                                       return s.request(method=method, url=url, **kwargs)
                                                     File "/storage/.kodi/addons/script.module.codequick/lib/urlquick.py", line 442, in request
                                                       self._raise_for_status(response, raise_for_status)
                                                     File "/storage/.kodi/addons/script.module.codequick/lib/urlquick.py", line 415, in _raise_for_status
                                                       response.raise_for_status()
                                                     File "/storage/.kodi/addons/script.module.requests/lib/requests/models.py", line 943, in raise_for_status
                                                       raise HTTPError(http_error_msg, response=self)
                                                   requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://edge.api.brightcove.com/playback/v1/accounts/4394098882001/videos/ref:ce6d3535-54b6-440e-85a3-5fb39e3e2e5c?User-Agent=Opera%2F9.80+%28X11%3B+Linux+i686%3B+Ubuntu%2F14.10%29+Presto%2F2.12.388+Version%2F12.16&Accept=application%2Fjson%3Bpk%3DBCpkADawqM1l5pA4XtMLusHj72LGzFewqKZzldpmNYTUQdoKnFL_GHhN3dg5FRnNQ5V7SOUKBl-tYFMt8CpSzuSzFAPhIHtVwmMz6F52VnMfu2UjDmeYfvvUqk0CWon46Yh-CZwIVp5vfXrZ&X-Forwarded-For=
2022-04-23 21:30:31.832 T:901     ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'HTTPError' object has no attribute 'code'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.catchuptvandmore/addon.py", line 23, in <module>
                                                       main()
                                                     File "/storage/.kodi/addons/plugin.video.catchuptvandmore/addon.py", line 19, in main
                                                       main.error_handler(exception)
                                                     File "/storage/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/main.py", line 290, in error_handler
                                                       code = exception.code
                                                   AttributeError: 'HTTPError' object has no attribute 'code'
                                                   -->End of Python script error report<--
                                                   
2022-04-23 21:30:32.090 T:901      INFO <general>: Python interpreter stopped
2022-04-23 21:30:32.378 T:774     ERROR <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.catchuptvandmore/resources/lib/channels/jp/tver/get_video_url/?_pickle_=800495a3000000000000007d94288c075f7469746c655f948c6fe7b4a0e4babae382b9e382bfe383bc21e5b290e9989ce381aee5a3b2e3828ce381aae38184e3839be382b9e38386e382b9e38286e38184e381a1e38283e38293e381abe383a9e382a4e38390e383abe799bbe5a0b4202834e69c883233e697a528e59c9f29e694bee98081e5888629948c065f617267735f948c07657069736f6465948c0a65706a7a76346b763962948694752e]

lol I always thought brightcove was bypassing geo-lock by replaying the video, proof me wrong :)  I can try to VPN into Japan and take a look.

**Comment by joaopa00** [comment]
Make some more changes
Now I manage to watch many videos.
Can you test with the latest version?

**Comment by kalun85** [comment]
@joaopa00 okay, it works, I was successfully able to watch a video.

When I go into the videos themselves and use ViewType = Wall.  The icons are not loaded.  Probably not a big deal to most people :)

My kodi is installed in LibreElec on a raspberry pi 4.  The loading time is quite long, probably because it needs to list all the video (I am guessing that's why you are asking)

To me, listing all the videos with Wall type was useful.  Because that allow me to easily look at who is in the video at a glance.  just my 2 cents

**Comment by kalun85** [comment]
@joaopa00  btw, thanks for fixing the plugin, awesome to see dev working on open source projects  :)

**Comment by joaopa00** [comment]
DO you know where the info about icons can be downloaded. In the provided there is nothing bout icons.

**Comment by kalun85** [comment]
@joaopa00 just tested.  Icon and description both works on new build

**Comment by joaopa00** [comment]
Thanks for testing. I will push the patch in git and release a beta version then.

**Comment by joaopa00** [comment]
Patch is in git. If it remains some problems, please open a new issue.
